### ISSUE TITLE
Formatting and Indenting of Code

### ISSUE THREAD

**Issue by cyouh95** [makizmo/prj-rev-bwfs-tea-cozy#1]
It seems like you're using tabs to indent in your code. But depending on the settings in your editor, the tabs could display differently in other environments. (For example, here, the indents look very large). Thus, alternatively, you could use spaces to indent (ie. 4 spaces for HTML and 2 spaces for CSS).

https://github.com/makizmo/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html
https://github.com/makizmo/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css

**Comment by makizmo** [comment]
Yes i used tab
it makes the arrange my work clearly
I'll definitely try the spaces as advised
